### PR TITLE
Initialise

### PR DESCRIPTION
**Pull request by mattgarner**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/dnanexus_nirvana2vcf/1)

### CODE REVIEW

**Review by woook — CHANGES_REQUESTED** [review]
Not sure how much work to put into this but pep8?

> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dnanexus_nirvana2vcf/1#-:-M-Rh4g36xwknGGsagQW:b-fecx4g)* status: 2 of 5 files reviewed, 22 unresolved discussions (waiting on @mattgarner and @woook)

___
*[dxapp.json, line 2 at r1](https://reviewable.io/reviews/eastgenomics/dnanexus_nirvana2vcf/1#-M-Rauxe9uD_tVxDGevc:-M-Rauxe9uD_tVxDGevd:b-6yx1h5) ([raw file](https://github.com/eastgenomics/dnanexus_nirvana2vcf/blob/1c241e81a1f6e929dc299d575e4e869108da13d7/dxapp.json#L2)):*
> ```JSON
> {
>   "name": "dnanexus_nirvana2vcf",
> ```

As per user guide, please can we include version in the name:
```Version number in app name
To avoid using archived apps on production runs any new apps must be seen as a new app. This is done by changing the name and title of the app (in dxapp.json) to include the version number.
```
___
*[resources/usr/bin/nirvana2vcf.py, line 9 at r1](https://reviewable.io/reviews/eastgenomics/dnanexus_nirvana2vcf/1#-M-Rfyu6E1dnVWP44j5f:-M-Rfyu6E1dnVWP44j5g:b-ewa69g) ([raw file](https://github.com/eastgenomics/dnanexus_nirvana2vcf/blob/1c241e81a1f6e929dc299d575e4e869108da13d7/resources/usr/bin/nirvana2vcf.py#L9)):*
> ```Python
> 
> import sys
> import subprocess
> ```

imported but unused
___
*[resources/usr/bin/nirvana2vcf.py, line 10 at r1](https://reviewable.io/reviews/eastgenomics/dnanexus_nirvana2vcf/1#-M-Rfxh-2U5fuQThqO2i:-M-Rfxh03dBr-2Rwh4nN:b-ewa69g) ([raw file](https://github.com/eastgenomics/dnanexus_nirvana2vcf/blob/1c241e81a1f6e929dc299d575e4e869108da13d7/resources/usr/bin/nirvana2vcf.py#L10)):*
> ```Python
> import sys
> import subprocess
> import os
> ```

imported but unused
___
*[resources/usr/bin/nirvana2vcf.py, line 12 at r1](https://reviewable.io/reviews/eastgenomics/dnanexus_nirvana2vcf/1#-M-Rbnb9DeRl4UvKiw6O:-M-Rbnb9DeRl4UvKiw6P:b-m6fehy) ([raw file](https://github.com/eastgenomics/dnanexus_nirvana2vcf/blob/1c241e81a1f6e929dc299d575e4e869108da13d7/resources/usr/bin/nirvana2vcf.py#L12)):*
> ```Python
> import os
> import argparse
> import re 
> ```

imported but unused
stray white space
___
*[resources/usr/bin/nirvana2vcf.py, line 19 at r1](https://reviewable.io/reviews/eastgenomics/dnanexus_nirvana2vcf/1#-M-RbwZ573w_VI0wLwPd:-M-RbwZ573w_VI0wLwPe:bgx80jp) ([raw file](https://github.com/eastgenomics/dnanexus_nirvana2vcf/blob/1c241e81a1f6e929dc299d575e4e869108da13d7/resources/usr/bin/nirvana2vcf.py#L19)):*
> ```
> //
> ```
I'm sure this is correct but I don't understand
___
*[resources/usr/bin/nirvana2vcf.py, line 20 at r1](https://reviewable.io/reviews/eastgenomics/dnanexus_nirvana2vcf/1#-M-Rg5dt712KKIkde3Ea:-M-Rg5dt712KKIkde3Eb:b-exf04b) ([raw file](https://github.com/eastgenomics/dnanexus_nirvana2vcf/blob/1c241e81a1f6e929dc299d575e4e869108da13d7/resources/usr/bin/nirvana2vcf.py#L20)):*
> ```Python
> 
> sys.path.append("/software/dev/lib//python2.7/site-packages/")
> import pysam
> ```

move up
___
*[resources/usr/bin/nirvana2vcf.py, line 23 at r1](https://reviewable.io/reviews/eastgenomics/dnanexus_nirvana2vcf/1#-M-RgEY64APITG3ANGUD:-M-RgEY64APITG3ANGUE:b-fgz129) ([raw file](https://github.com/eastgenomics/dnanexus_nirvana2vcf/blob/1c241e81a1f6e929dc299d575e4e869108da13d7/resources/usr/bin/nirvana2vcf.py#L23)):*
> ```Python
> 
> 
> def open_file( filename ):
> ```

why whitespace in brackets?
___
*[resources/usr/bin/nirvana2vcf.py, line 24 at r1](https://reviewable.io/reviews/eastgenomics/dnanexus_nirvana2vcf/1#-M-Rc3Pd0Y7oug7nIM-u:-M-Rc3Pd0Y7oug7nIM-v:bc02azu) ([raw file](https://github.com/eastgenomics/dnanexus_nirvana2vcf/blob/1c241e81a1f6e929dc299d575e4e869108da13d7/resources/usr/bin/nirvana2vcf.py#L24)):*
> ```Python
> 
> def open_file( filename ):
>     
> ```

white space
___
*[resources/usr/bin/nirvana2vcf.py, line 36 at r1](https://reviewable.io/reviews/eastgenomics/dnanexus_nirvana2vcf/1#-M-RgNU52nGKHQTVC3bi:-M-RgNU52nGKHQTVC3bj:b32x0h) ([raw file](https://github.com/eastgenomics/dnanexus_nirvana2vcf/blob/1c241e81a1f6e929dc299d575e4e869108da13d7/resources/usr/bin/nirvana2vcf.py#L36)):*
> ```Python
> 
> 
> def readin_json( filename ):
> ```

ws
___
*[resources/usr/bin/nirvana2vcf.py, line 38 at r1](https://reviewable.io/reviews/eastgenomics/dnanexus_nirvana2vcf/1#-M-RgOTtEgyNtWRLwmaQ:-M-RgOTtEgyNtWRLwmaR:b32x0h) ([raw file](https://github.com/eastgenomics/dnanexus_nirvana2vcf/blob/1c241e81a1f6e929dc299d575e4e869108da13d7/resources/usr/bin/nirvana2vcf.py#L38)):*
> ```Python
> def readin_json( filename ):
> 
>     json_data = open_file( filename )
> ```

ws
___
*[resources/usr/bin/nirvana2vcf.py, line 45 at r1](https://reviewable.io/reviews/eastgenomics/dnanexus_nirvana2vcf/1#-M-RgQm43vXA3NktD1dX:-M-RgQm43vXA3NktD1dY:b32x0h) ([raw file](https://github.com/eastgenomics/dnanexus_nirvana2vcf/blob/1c241e81a1f6e929dc299d575e4e869108da13d7/resources/usr/bin/nirvana2vcf.py#L45)):*
> ```Python
> 
> 
> def merge_files( vcf_file, json_file, out_file):
> ```

ws
___
*[resources/usr/bin/nirvana2vcf.py, line 55 at r1](https://reviewable.io/reviews/eastgenomics/dnanexus_nirvana2vcf/1#-M-RcCr_0WF_ltumnn5Q:-M-RcCr_0WF_ltumnn5R:bc02azu) ([raw file](https://github.com/eastgenomics/dnanexus_nirvana2vcf/blob/1c241e81a1f6e929dc299d575e4e869108da13d7/resources/usr/bin/nirvana2vcf.py#L55)):*
> ```Python
>         None
> 
>     
> ```

white space
___
*[resources/usr/bin/nirvana2vcf.py, line 62 at r1](https://reviewable.io/reviews/eastgenomics/dnanexus_nirvana2vcf/1#-M-RgZH102Siv0UIHoLI:-M-RgZH102Siv0UIHoLJ:b32x0h) ([raw file](https://github.com/eastgenomics/dnanexus_nirvana2vcf/blob/1c241e81a1f6e929dc299d575e4e869108da13d7/resources/usr/bin/nirvana2vcf.py#L62)):*
> ```Python
>     out_fh = open(out_file, "w")
> 
>     annotations = readin_json( json_file )
> ```

ws
___
*[resources/usr/bin/nirvana2vcf.py, line 63 at r1](https://reviewable.io/reviews/eastgenomics/dnanexus_nirvana2vcf/1#-M-RcFFuAQEActA64aRa:-M-RcFFuAQEActA64aRb:b-tii2jk) ([raw file](https://github.com/eastgenomics/dnanexus_nirvana2vcf/blob/1c241e81a1f6e929dc299d575e4e869108da13d7/resources/usr/bin/nirvana2vcf.py#L63)):*
> ```Python
> 
>     annotations = readin_json( json_file )
>     
> ```

white space and all the other random white space below
___
*[resources/usr/bin/nirvana2vcf.py, line 64 at r1](https://reviewable.io/reviews/eastgenomics/dnanexus_nirvana2vcf/1#-M-RgVd31pmSjPwwm8uH:-M-RgVd31pmSjPwwm8uI:b32x0h) ([raw file](https://github.com/eastgenomics/dnanexus_nirvana2vcf/blob/1c241e81a1f6e929dc299d575e4e869108da13d7/resources/usr/bin/nirvana2vcf.py#L64)):*
> ```Python
>     annotations = readin_json( json_file )
>     
>     vcf_in = pysam.VariantFile( vcf_file )
> ```

ws
___
*[resources/usr/bin/nirvana2vcf.py, line 70 at r1](https://reviewable.io/reviews/eastgenomics/dnanexus_nirvana2vcf/1#-M-RgiGX0DLjCrrYlrkM:-M-RgiGX0DLjCrrYlrkN:bukkm6u) ([raw file](https://github.com/eastgenomics/dnanexus_nirvana2vcf/blob/1c241e81a1f6e929dc299d575e4e869108da13d7/resources/usr/bin/nirvana2vcf.py#L70)):*
> ```
> ( '
> ```
ws
___
*[resources/usr/bin/nirvana2vcf.py, line 72 at r1](https://reviewable.io/reviews/eastgenomics/dnanexus_nirvana2vcf/1#-M-RclG33C0HGhfVxoaU:-M-RclG33C0HGhfVxoaV:b7o8k19) ([raw file](https://github.com/eastgenomics/dnanexus_nirvana2vcf/blob/1c241e81a1f6e929dc299d575e4e869108da13d7/resources/usr/bin/nirvana2vcf.py#L72)):*
> ```Python
>     vcf_in.header.add_line( '##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence type as predicted by VEP. Format: Allele|Gene|HGNC|RefSeq|Feature|Consequence|cDNA_position|Protein_position|Amino_acids|Existing_variation|SIFT|PolyPhen|HGVSc">')
> 
> #    vcf_in.header.remove_line("CSQT")
> ```

Does this need to be here?
___
*[resources/usr/bin/nirvana2vcf.py, line 74 at r1](https://reviewable.io/reviews/eastgenomics/dnanexus_nirvana2vcf/1#-M-RcqU8Br0RIqPqmMpz:-M-RcqU8Br0RIqPqmMq-:b7o8k19) ([raw file](https://github.com/eastgenomics/dnanexus_nirvana2vcf/blob/1c241e81a1f6e929dc299d575e4e869108da13d7/resources/usr/bin/nirvana2vcf.py#L74)):*
> ```Python
> #    vcf_in.header.remove_line("CSQT")
> 
> #    vcf_in.header.add_line( '##source_nirvana= Nirvana X.XXXX')
> ```

Does this need to be here?
___
*[resources/usr/bin/nirvana2vcf.py, line 77 at r1](https://reviewable.io/reviews/eastgenomics/dnanexus_nirvana2vcf/1#-M-Rcs0G55TzS-BwEvfm:-M-Rcs0G55TzS-BwEvfn:b7o8k19) ([raw file](https://github.com/eastgenomics/dnanexus_nirvana2vcf/blob/1c241e81a1f6e929dc299d575e4e869108da13d7/resources/usr/bin/nirvana2vcf.py#L77)):*
> ```Python
> 
>     # print the vcf header
>     #sys.stdout.write(str( vcf_in.header ))
> ```

Does this need to be here?
___
*[resources/usr/bin/nirvana2vcf.py, line 84 at r1](https://reviewable.io/reviews/eastgenomics/dnanexus_nirvana2vcf/1#-M-Rcxo451e9QUCZ3Uja:-M-Rcxo451e9QUCZ3Ujb:b7o8k19) ([raw file](https://github.com/eastgenomics/dnanexus_nirvana2vcf/blob/1c241e81a1f6e929dc299d575e4e869108da13d7/resources/usr/bin/nirvana2vcf.py#L84)):*
> ```Python
>     # Loop through each of the vcrf entries.
>     for rec_index, rec in enumerate(vcf_in.fetch()):
> #        print rec
> ```

Does this need to be here?
___
*[resources/usr/bin/nirvana2vcf.py, line 95 at r1](https://reviewable.io/reviews/eastgenomics/dnanexus_nirvana2vcf/1#-M-Rd1UGCGPh446Xkb5A:-M-Rd1UGCGPh446Xkb5B:be4qcab) ([raw file](https://github.com/eastgenomics/dnanexus_nirvana2vcf/blob/1c241e81a1f6e929dc299d575e4e869108da13d7/resources/usr/bin/nirvana2vcf.py#L95)):*
> ```Python
> 
>         assert (vcf_chrom == json_chrom) and (vcf_pos == json_pos), "vcf and json out of sync at vcf line %d! Aborting." % variant_counter
>             #print "Mismatch:"
> ```

Lots of commented out lines...
___
*[src/dnanexus_nirvana2vcf.sh, line 49 at r1](https://reviewable.io/reviews/eastgenomics/dnanexus_nirvana2vcf/1#-M-RhWEg-EWR6rU1Z7VA:-M-RhWEg-EWR6rU1Z7VB:b32x0h) ([raw file](https://github.com/eastgenomics/dnanexus_nirvana2vcf/blob/1c241e81a1f6e929dc299d575e4e869108da13d7/src/dnanexus_nirvana2vcf.sh#L49)):*
> ```Shell
> 
>     output_vcf_name="${json_file_prefix}.refseq_nirvana_203.annotated.vcf"
>         
> ```

ws

**Review by mattgarner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dnanexus_nirvana2vcf/1)* status: 2 of 5 files reviewed, 22 unresolved discussions (waiting on @mattgarner and @woook)

___
*[dxapp.json, line 2 at r1](https://reviewable.io/reviews/eastgenomics/dnanexus_nirvana2vcf/1#-M-Rauxe9uD_tVxDGevc:-M0r1jVH1oMI4jAOU01j:b-78v45y) ([raw file](https://github.com/eastgenomics/dnanexus_nirvana2vcf/blob/1c241e81a1f6e929dc299d575e4e869108da13d7/dxapp.json#L2)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

As per user guide, please can we include version in the name:
```Version number in app name
To avoid using archived apps on production runs any new apps must be seen as a new app. This is done by changing the name and title of the app (in dxapp.json) to include the version number.
```
</blockquote></details>

Updated name and title to include version. Also included eggd_ prefix on name, title, summary
___
*[resources/usr/bin/nirvana2vcf.py, line 12 at r1](https://reviewable.io/reviews/eastgenomics/dnanexus_nirvana2vcf/1#-M-Rbnb9DeRl4UvKiw6O:-M0r260b-eygoVxxJWt1:bhn7q6f) ([raw file](https://github.com/eastgenomics/dnanexus_nirvana2vcf/blob/1c241e81a1f6e929dc299d575e4e869108da13d7/resources/usr/bin/nirvana2vcf.py#L12)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

imported but unused
stray white space
</blockquote></details>

As discussed in person, style issues will be addressed in future release if code is still used
___
*[src/dnanexus_nirvana2vcf.sh, line 49 at r1](https://reviewable.io/reviews/eastgenomics/dnanexus_nirvana2vcf/1#-M-RhWEg-EWR6rU1Z7VA:-M0r2hdYA5t2mWlT_ed5:b4s61nl) ([raw file](https://github.com/eastgenomics/dnanexus_nirvana2vcf/blob/1c241e81a1f6e929dc299d575e4e869108da13d7/src/dnanexus_nirvana2vcf.sh#L49)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

ws
</blockquote></details>

ws removed

**Comment by woook** [comment]
:lgtm:

**Review by woook — APPROVED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_nirvana2vcf/1#-:-M1k8csf9Zyp9XDN8CZo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
